### PR TITLE
Fix the failure of chiral centre detection

### PR DESCRIPTION
**Pull request by raimis**
- [x] Preserve initial molecule
- [x] Make the chiral centre detector to accept custom atom types
- [x] Pass the initial atom types to the chiral centre detector

### CODE REVIEW

**Comment by raimis** [comment]
@cuzzo87 Here is the fix for you! Check and review it.

**Comment by cuzzo87** [comment]
For the error I was mentioning this fix should solve the problem. Anyway, did you try to load/parameterize the output.mol2 of parameterize ? If I recall correct, the reason for having the `atomtypes=element` was because rdkit cannot read our atomtypes. Can you check this ?

**Comment by raimis** [comment]
Yes, it will fail with wrong types. As I said, this makes the user responsible for correct atom types, because `atomtype=element` is not good for rdkit.

**Comment by cuzzo87** [comment]
For me it is ok.

**Comment by raimis** [comment]
@cuzzo87 you need to approve, so I can merge.

**Pull request merged**
