### PR TITLE
Tests and Travis fixes for new paradigm

### PR DESCRIPTION
**Pull request by j3mdamas**
* Removes some test files which are outdated/deprecated
* Should fix the problems on PR Travis builds, but avoiding using the secure environment variables or having a fail-safe for them:
    * Only clones htmdlib of not PR, and if credentials do not work for cloning, it carries on with the DSOs 
      on the repo
    * HTMD_NONINTERACTIVE explicitly set, LICENSE_TOKEN removed

### CODE REVIEW

**Comment by j3mdamas** [comment]
I removed more tests and added the MacOS lib files (they were missing in the repository, so the PR failed for Mac). You need to re-approve :)

**Comment by stefdoerr** [comment]
You need to fix the run_other_tests.sh script

**Comment by j3mdamas** [comment]
Yeah, yeah, will do tomorrow...

**Comment by j3mdamas** [comment]
Done, can be merged when you approve it.

**Pull request merged**
