### PR TITLE
Silence pyemma version warnings

### PR DESCRIPTION
**Pull request by stefdoerr**
Really the other PR was overkill. Those warnings are only thrown on the first import. So we might as well just import it once with a wrapper in `htmd.ui` and be done with it.

### CODE REVIEW

**Comment by stefdoerr** [comment]
@j3mdamas this is another very trivial PR for a 1 second review. The only question is if we care about the flows. If someone import directly Model or TICA without using `ui` it will still throw the pyemma warning. But I personally don't think we care that much about this case

**Comment by stefdoerr** [comment]
I mean I could silence the warning in those files as well but I don't feel like splattering this stuff all around the HTMD code

**Comment by j3mdamas** [comment]
I assume we do not want to do it on the `__init__.py`, right?
I think for the Flows, we could put such a code there as well.

**Comment by stefdoerr** [comment]
No, it would slow down all import in the init. Thanks!

**Pull request merged**
