### PR TITLE
Improvements for PDB reader

### PR DESCRIPTION
**Pull request by stefdoerr**
This PR should fix the following two issues:
https://github.com/Acellera/htmd/issues/708 Hydrogen detected as Hahnium
https://github.com/Acellera/htmd/issues/712 Reading resnames starting with zeros

### CODE REVIEW

**Comment by stefdoerr** [comment]
This one is actually easier @j3mdamas :P Won't hurt as much as the last one.

**Comment by stefdoerr** [comment]
Depends on https://github.com/Acellera/htmd-data/pull/4 being merged as now our PDBreader will fail on broken PDB files (which it should)

**Comment by j3mdamas** [comment]
The best (and worst) thing about the submodule, is that we can merge this and it will still reference the right commit (even though you did well with the branch and PR there, that's what I've been doing as well)

**Comment by j3mdamas** [comment]
merging it

**Pull request merged**
