### PR TITLE
fix adaptive base for saving PDBs

### PR DESCRIPTION
**Pull request by giadefa**
Simplify the writing of new coordinates that works also when the new coordinate file is a PDB.

The previous optimization is probably not important as this is not a critical part for performance

### CODE REVIEW

**Comment by stefdoerr** [comment]
Could you possibly just make it check if the `coor` extension is a key in the `_TOPOLOGY_READERS` dictionary of `htmd/molecule/readers.py`? Then if it is, it will read the topology to write it out again, otherwise not. I remember that this change was to support use cases for MD engines where we don't have topology readers but still can make it work if they write in a compatible trajectory format, i.e. `pmemd`. Also reduces warning-spam from the readers and makes it faster for stuff like any sort of fake or synthetic adaptive where you might spawn hundreds of simulations.

**Comment by giadefa** [comment]
The way it is, it always read the mol file, so it would work in all cases

**Comment by giadefa** [comment]
if htmd cannot read the mol file, then it cannot do anything really even if you can write out a coordinate file. The solution would be to add the missing reader

**Comment by giadefa** [comment]
second motivation is that if we do checks like that, we actually make the code unusable because to fix a corner case another one is broken (as in this case). Code should be minimalistic.

**Comment by giadefa** [comment]
@j3mdamas  The assignee is the one that should approve it or the one that made the PR?

**Comment by stefdoerr** [comment]
We agreed to put as assignee the one that writes the code and the reviewer is the reviewer

On April 4, 2018 1:52:30 PM GMT+03:00, Gianni De Fabritiis <notifications@github.com> wrote:
>@j3mdamas  The assignee is the one that should approve it or the one
>that made the PR?
>
>-- 
>You are receiving this because your review was requested.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/pull/630#issuecomment-378559936

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefdoerr** [comment]
Ok fine. We don't use the synthetic adaptive anymore anyway and this would make it more flexible.

On April 4, 2018 2:34:21 PM GMT+03:00, stefdoerr@gmail.com wrote:
>We agreed to put as assignee the one that writes the code and the
>reviewer is the reviewer
>
>On April 4, 2018 1:52:30 PM GMT+03:00, Gianni De Fabritiis
><notifications@github.com> wrote:
>>@j3mdamas  The assignee is the one that should approve it or the one
>>that made the PR?
>>
>>-- 
>>You are receiving this because your review was requested.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/Acellera/htmd/pull/630#issuecomment-378559936
>
>-- 
>Sent from my Android device with K-9 Mail. Please excuse my brevity.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefdoerr** [comment]
We need to merge the master in here to pass the tests still

**Comment by j3mdamas** [comment]
master needs to be merged into this in order to execute the ci tests

**Comment by j3mdamas** [comment]
@giadefa you can merge now, the master has now the fixes for passing travis

**Comment by j3mdamas** [comment]
I meant merge master into this PR.

**Comment by j3mdamas** [comment]
I'll fix it, don't worry.

**Pull request merged**
