### PR TITLE
Adaptive nepochs fix

### PR DESCRIPTION
**Pull request by j3mdamas**
@stefdoerr can you check if this is fine?

Before this change, at the first updateperiod after the submission of the last epoch, the adaptive would end regardless if there were still simulations running or not (depending on the nmin and nmax, it could mean 1 or 2 epochs less of trajectories).

I've tested it and it seems like it does not break, can you check and accept the pull request?

### CODE REVIEW

**Comment by j3mdamas** [comment]
maybe wait for Travis and then accept

**Comment by stefdoerr** [comment]
Yes, yes I will check. But tomorrow. I'm finishing OPM today

**Comment by j3mdamas** [comment]
sure, whenever you have time

**Comment by stefdoerr** [comment]
I checked anyways :) It's good.

My only miiiinor gripe is the time wasted checking inprogress() everytime we call it once it's done but it's unavoidable unless we set somewhere a `finished` flag in a file or something which would be too much mess.

Thanks for the fix :)

**Comment by j3mdamas** [comment]
You didn't merge, just closed, but I'll merge now

**Pull request merged**
