### PR TITLE
bugfix for fftype. Masses are usually correct length but zeros

### PR DESCRIPTION
**Pull request by stefdoerr**
The check to substitute masses in fftype was wrong. Fixed it now

### CODE REVIEW

**Comment by raimis** [comment]
I have a feeling with won't pass the tests... :D

**Comment by stefdoerr** [comment]
Hmmm we might get away with it since `mol2` files don't contain masses :smile:

**Comment by stefdoerr** [comment]
That was wishful thinking :P But ok it's just cgenff tests not passing due to masses in rtf. I'll fix it quick

**Comment by stefdoerr** [comment]
@raimis it passes. Are you ok with a merge?

**Pull request merged**
