### PR TITLE
Cleaned up file reading in Molecule

### PR DESCRIPTION
**Pull request by stefdoerr**
All read functions now return a Topology and a Trajectory object.
All functions also take same arguments.

This allows us to have multiple readers for the same extension (i.e. .top which is both GROMACS and AMBER topologies, or .crd which can be CHARMM or ...something else) irrespective of the kind of file it is: topology / trajectory etc.

Also much more readable code now.

### CODE REVIEW

**Comment by j3mdamas** [comment]
Travis is failing like crazy on these, maybe unrelated?

**Comment by stefdoerr** [comment]
It's been failing since yesterday but due to conda problems as far as I can
tell

But this PR probably also has bugs considering that it's a change to the
deep guts of HTMD

**Comment by j3mdamas** [comment]
As such, this really needs to pass Travis.

**Comment by stefdoerr** [comment]
Which is indeed why I haven't merged yet :P And why I put you two as reviewers, haha

**Comment by stefdoerr** [comment]
Ok, it passed the tests (minus OSX failing as always).
I would probably just wait until Friday to merge so that you can make a safe release tomorrow?

**Comment by j3mdamas** [comment]
Let's see how the last build goes. I will merge it, it's OK.

**Pull request merged**
