### PR TITLE
Added support for multimol Mol2 files

### PR DESCRIPTION
**Pull request by stefdoerr**
Updated the old mol2 reader. Made it able to read multimol files.
Molecule class will still not be able to read multimol files since this will require a decent redesign of stuff. But at least if someone wishes to use the reader directly to read multiple mol2 molecules he can. 
I'll probably make another PR later that allows `Molecule.read` to read and return multiple molecules.

### CODE REVIEW

**Comment by j3mdamas** [comment]
@stefdoerr can you setup a priority for this? thanks!

**Comment by stefdoerr** [comment]
Considering it's a small change, the sooner the better because you know how much fun it is to merge branches and updates :P Let's see though if the tests pass. But really it's just a 5 minutes review max.

**Comment by stefdoerr** [comment]
It's not urgent though in any sense because I doubt it will manage to make
it to the current smallmol without some hacking

**Comment by stefdoerr** [comment]
Took you too long ;) Now you will suffer the consequences. I close this to open soon a much bigger PR which refactors the readers and Molecule.read.

**Pull request closed without merging**
