### PR TITLE
Better parametrize testing

### PR DESCRIPTION
**Pull request by stefdoerr**
I am trying to replace the file comparison in parametrize tests with an actual energy evaluation. 

1. it compares all non-dihedral parameters for exact matching
2. it evaluates the energy of the dihedrals of both parametrizations and calculates the RMSE

TODO:

- [x] Implement it in the tests
- [ ] Remove file comparison for `frcmod` and `prm`
- [ ] Determine the threshold for the RMSE of two fits

### CODE REVIEW

**Comment by stefdoerr** [comment]
As in this branch all tests are deterministic and no changes were made to the parametrization I cannot determine a good RMSE (it's 0 right now). So if everyone is fine with it I will merge this into `master` and from there merge it to `dihedralnumba` branch where I can see how different my results are.

@raimis if you can give this a look it would be great

**Comment by j3mdamas** [comment]
@stefdoerr this is an incomplete PR, right? Right now, what was merged is just adding some `Molecule`, and "parmed" parameter class comparisons to what was already being done and not actually replacing anything. Can you explain better the merge since I don't understand it from https://github.com/Acellera/htmd/pull/556#issuecomment-364173039?

**Comment by stefdoerr** [comment]
I needed to determine  a threshold for the energy difference when testing. Since this branch would give 0 energy difference as nothing changed in the actual parametrization code I needed to merge it into dihedralnumba class which actually gave divergent results to determine a good threshold. It's not incomplete. It's merged :P

**Comment by j3mdamas** [comment]
You need to explain it to me tomorrow, because I don't understand this PR as it is not achieving what you said in the OP, and I don't understand why what you added (which is great, I'm not criticising the actual code of the PR) gives "0 energy difference".

Is this zero energy difference to pass the tests? If it is, I don't know how it's helping passing them, as the `energies.txt` file is still being compared on the `_test()`.

**Comment by j3mdamas** [comment]
Furthermore, you could have always merged this branch into the "numba" branch, without needing to "pass through" master.

**Comment by stefdoerr** [comment]
Did that last time and ended up duplication commits and making an
unreadable PR.

**Comment by stefdoerr** [comment]
The `energy.txt` gives you total energy difference between the two parametrizations. What I cared about was the RMSE of the two fitted curves to each other (new one versus the one in htmd/data/test-param) to make sure that the fits don't get worse then the old ones. To do that I evaluate old and new parameters at all 36 rotamers and get the rmse. That is what the code does and it is implemented in commit https://github.com/Acellera/htmd/pull/556/commits/b1e1bd31bd3342882c230efa048b3cc13a0ba873#diff-30df3daf0d6dd9196a6be06176a32d20

In this PR if you ran the tests, the parametrization you produce is identical to the one in the tests. Hence the RMSE of the two curves is 0.

**Comment by j3mdamas** [comment]
Sorry Stefan, for a reason I was seeing a wrong diff, where I didn't see `_compareDihedralEnergies`.

**Comment by j3mdamas** [comment]
More correctly, I was overlooking it.

**Comment by j3mdamas** [comment]
Amazing code btw! :D I just think that the PR post should actually reflect what was done in the PR :P 

Just a small critique: the way you did it is not the same as comparing the dihedral plots. The dihedral plots are generated from the energies of the final minimized configurations that can be found on each folder inside each angle of each dihedral, while you are comparing the initial configurations (you are generating them in the same way that is generated for the QM calculation). I guess the way to compare equal to comparing the plots would be to compare the energies given by the final configurations found in `dihedral/<dihedral-name>/<dihedral-angle>`. Or even better would be to output the raw values that are used on the plots in a text file and compare those xD

As a positive part, you test actually tests even when dihedrals are not parameterized.

**Comment by raimis** [comment]
@stefdoerr 

@j3mdamas  is right, it could be done simple outputting plot data and comparing just file.

Another issue, you are using functions for reference data, which are suppose to be tested. So the test are not testing what they are suppose to test.

**Comment by stefdoerr** [comment]
I don't see why write another temp file when I can do the comparisson by evaluation which is more or less the ultimate test. Plus it gives more flexibility.
@j3mdamas Ok I will use the final conformations. Didn't know that
@raimis I don't understand what you mean with functions for reference data.

**Comment by j3mdamas** [comment]
Actually, I don't think the raw data of the plots would be a temporary file, I really think we should output it (and use it, since it's there), as users may want to redo the dihedrals plot some other way. @Acellera/gerard already mentioned that before.

**Pull request merged**
