### PR TITLE
Parmed 3 fix

### PR DESCRIPTION
**Pull request by stefdoerr**
This makes HTMD compatible with parmed 3+ but breaks compatibility with parmed 2.7.
It will not pass the tests here since we would need to update parmed on acellera channel but I tested it locally and it passes all tests. 

https://github.com/ParmEd/ParmEd/issues/990
As per this issue I had to implement improper center detection to be compatible with the new way it stores impropers.

### CODE REVIEW

**Comment by stefdoerr** [comment]
I made it work for both parmed 2.7 and 3 now! So we can merge with no issues. Also simplified a bit the code and the usage

**Comment by j3mdamas** [comment]
This now depends on #729, no?

**Comment by stefdoerr** [comment]
Nah, just on the docstrings which are not evaluated on testing.

**Comment by j3mdamas** [comment]
it's merged in any case :)

**Pull request merged**
