### PR TITLE
Atom groups for custom distance metrics

### PR DESCRIPTION
**Pull request by stefdoerr**
Add support for any kind of grouping for distances including center of masses, min, max dist and geometric center.

### CODE REVIEW

**Comment by j3mdamas** [comment]
Thanks! So, now `MetricDistance` needs some refactoring to use this class and htmdlib needs new calculators for the different types of distances. Do you want me to do it?

**Comment by stefdoerr** [comment]
If you are that bored go ahead

**Comment by j3mdamas** [comment]
I've discussed this with @stefdoerr and we're finishing it on 1.14

**Comment by j3mdamas** [comment]
Hi @stefdoerr,
I don't know what this is anymore, but I guess you can push to master or close it.

**Pull request closed without merging**
