### PR TITLE
Capture stderr messages in case of RDKit failures

### PR DESCRIPTION
**Pull request by raimis**
- [x] Implement `_convertMoleculeToRDKitMol`
- [x] Capture RDKit failures in `detectChiralCenters`
- [x] Capture RDKit failures in `fitGasteigerCharges`

### CODE REVIEW

**Comment by raimis** [comment]
@stefdoerr could you review, please.

If there is a better place for `_convertMoleculeToRDKitMol` rather than `htmd/util.py`, let me know.

**Comment by stefdoerr** [comment]
Yeah it ought to go to `moleculekit/util.py`. I can add it but we will need to make a new release

**Comment by raimis** [comment]
At the moment, I can build the app using this branch, so the new release can happen whenever you ready.

**Comment by stefdoerr** [comment]
Added it to `moleculekit.rdkitintegration` https://github.com/Acellera/moleculekit/blob/master/moleculekit/rdkitintegration.py#L14

Currently making a new release 
https://travis-ci.org/Acellera/moleculekit/builds/554314016
If it passes you can try this PR with moleculekit 0.1.10 and change your imports

**Comment by stefdoerr** [comment]
I will pre-approve the PR since I'll be out next week so that you can merge.

**Pull request merged**
