### PR TITLE
added spherical coordinate metric for Alberto

### PR DESCRIPTION
**Pull request by stefdoerr**

### CODE REVIEW

**Comment by j3mdamas** [comment]
It seems good to me. @cuzzo87 is going to test it with his trajectories and then we merge it. Thanks!

**Comment by cuzzo87** [comment]
I will test it this afternoon. Thx

**Comment by cuzzo87** [comment]
First set of testing, suggests that the arctan function should be arctan2. I will tried and in case fix it

**Comment by j3mdamas** [comment]
I thought we're supposed to only merge if this was working? @stefdoerr?

**Comment by stefdoerr** [comment]
Oops. That was an accident. It must have remembered me accepting it and auto-merged it now that I changed the rules. Check my mail

**Comment by j3mdamas** [comment]
I saw it. It's OK. Let's see if this can be improved in the future

**Comment by stefdoerr** [comment]
@cuzzo87 so was it arctan2? Cause we never fixed it on HTMD

**Comment by cuzzo87** [comment]
I had a couple of test with both. Based on them I would use arctan2.

**Pull request merged**
