### PR TITLE
Fix angle and dihedral guessing code

### LINKED ISSUE #441: Dihedral angle guessing is broken for cyclopropane
Let's guess the dihedral angles of [cyclopropane .mol2.txt](https://github.com/Acellera/htmd/files/1270145/cyclopropane.mol2.txt):
```python
>>> from htmd.molecule.molecule import Molecule
>>> from htmd.molecule.vmdparser import guessAnglesAndDihedrals
>>> m = Molecule('cyclopropane.mol2')
>>> a, d = guessAnglesAndDihedrals(m.bonds)
```

It should be **27** of them, but we got just **25**:
```python
>>> len(d)
25
```

Also, this `[0, 2, 1, 1]` obviously is incorrect:
```python
>>> d
array([[0, 2, 1, 3],
       [0, 2, 1, 4],
       [0, 2, 1, 5],
       [0, 2, 1, 1],
       [1, 3, 2, 0],
       [0, 2, 3, 7],
       [0, 2, 3, 8],
       [3, 1, 2, 6],
       [2, 1, 3, 7],
       [2, 1, 3, 8],
       [3, 2, 1, 4],
       [3, 2, 1, 5],
       [1, 2, 3, 7],
       [1, 2, 3, 8],
       [4, 1, 2, 6],
       [5, 1, 2, 6],
       [2, 3, 1, 4],
       [2, 3, 1, 5],
       [1, 3, 2, 6],
       [4, 1, 3, 7],
       [4, 1, 3, 8],
       [5, 1, 3, 7],
       [5, 1, 3, 8],
       [6, 2, 3, 7],
       [6, 2, 3, 8]])
```

### PR DESCRIPTION
**Pull request by raimis**
- [x] Fix #441
- [x] Sort angle and dihedrals
- [x] Update `parameterize` tests

### CODE REVIEW

**Comment by raimis** [comment]
@stefdoerr, this is ready for reviewing and merging.

**Comment by stefdoerr** [comment]
I was wondering. Do you really want to return duplicate (inverted) dihedrals and angles? The old function didn't do that

**Comment by raimis** [comment]
There are no duplicates, just some inverted angles and dihedrals, if the atomic indices looks "nicer".

**Comment by stefdoerr** [comment]
Ah yes right I see now

**Comment by raimis** [comment]
@stefdoerr this pull request was on ` Acellera:fixguessangles `, so you need to merge to `master` too.

**Comment by stefdoerr** [comment]
done

**Pull request merged**
