### PR TITLE
Added Radii.

### PR DESCRIPTION
**Pull request by miha-skalic**

### CODE REVIEW

**Comment by stefdoerr** [comment]
Please document where the values came from and what those atoms are

**Comment by hawk31** [comment]
Let's try and make it consistent. Two decimals, rounding to the nearest decimal instead of removing them, etc.

**Comment by j3mdamas** [comment]
+1 @stefdoerr comment.

**Comment by miha-skalic** [comment]
Updated.
@stefdoerr @hawk31

**Pull request closed without merging**
