### PR TITLE
New non-linear htmd-data to fix stable/latest forked nature

### PR DESCRIPTION
**Pull request by j3mdamas**
So, this is my proposal to fix https://github.com/Acellera/htmd/issues/660

This PR includes:

* htmd-data moved from this repo to https://github.com/Acellera/htmd-data
* sub-module the new htmd-data repo to the same place

(these two include are staight-forward integration with the previous c-i, worked perfectly out of the box)

* htmd-data build and installation re-factored
   - new conda_build_htmd-data.sh aux file which creates a package based on the submodule hash (solves conflicting version bumps cleanly, works well with not releasing too many versions and only when there are changes in the submodule)
   - fix on the htmd-data version that is put on htmd-deps (https://github.com/Acellera/htmd/issues/660#issuecomment-388880790)

As soon as this gets accepted, I can finally release cleanly without risking breaking tested deployments (that depend on htmd-data)

### CODE REVIEW

**Comment by stefdoerr** [comment]
It looks good. But could you please restate clearly what the problem was? 
If we have a stable and master branch, what's the problem with adding tests from master to stable or vice versa? And each one releasing it's own htmd-data package? Isn't it easier to just release an htmd-data with a stable version to match the HTMD stable version?
I don't understand why data creates a problem when it works with the code.

**Comment by j3mdamas** [comment]
Currently htmd-data goes with version bumps on code: in package/htmd-data/meta.yaml. This means linear versioning and minimization of packaging for htmd-data. Don't forget release of data only works at version bump and not at every release of HTMD (so we don't release data too many times)

Htmd itself is non-linear: it has stable and latest versions. Both need to be able to be tested on deployment, not only stable.

Let me give a practical example: both stable and latest are releasing htmd-data 0.0.47. I do changes in the data for latest, and I bump version to 0.0.48. and then again and bump to version 0.0.49. Then, I want to make changes in data due to a fix in stable, which version do I bump to? And even if I bump to 0.0.50, when I merge the fix into master, how will the conflict be solved?

I am not claiming this is the only solution, but it was the cleanest I found. If you have a simpler alternative, please let me know.

**Comment by j3mdamas** [comment]
It's here: https://github.com/Acellera/htmd/pull/683/commits/9e0786d3bb55bc6d8a115cff6f13f7074669259d

It's hard to review with all the data deletion.

**Comment by j3mdamas** [comment]
Or rather the final version here: https://github.com/Acellera/htmd/blob/181662836a5cb8d4a420fcfa4034cabed58b6b8f/continuous-integration/travis/conda_build_htmd-data.sh#L12

**Comment by j3mdamas** [comment]
Moving to a separate repo allows perfect and automated referencing.

In conda, we can clone a repo (like we do when we clone from other channels to our own) but it still occupies space.

I just kept numbering out of convenience, to keep the *.*.* scheme. But I can drop it, I think there should be no conda issue with it.

**Comment by j3mdamas** [comment]
No, no. That's the advantage of the submodule. Changes inside the submodule aren't changes to the htmd module. Think of it as a dependency that you have right there inside the repo.

Here's some commands to try to exemplify what's going on:
```
[joao@computer02 htmd]$ pwd
/home/joao/maindisk/software/repos/Acellera/htmd/htmd
[joao@computer02 htmd]$ git status
# On branch newhtmddata
nothing to commit, working directory clean
[joao@computer02 htmd]$ git remote -v
origin	git@github.com:Acellera/htmd.git (fetch)
origin	git@github.com:Acellera/htmd.git (push)
[joao@computer02 htmd]$ cd data/
[joao@computer02 data]$ git status
# On branch master
nothing to commit, working directory clean
[joao@computer02 data]$ git remote -v
origin	git@github.com:Acellera/htmd-data.git (fetch)
origin	git@github.com:Acellera/htmd-data.git (push)
[joao@computer02 data]$ > newfile
[joao@computer02 data]$ git status
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	newfile
nothing added to commit but untracked files present (use "git add" to track)
[joao@computer02 data]$ cd ../
[joao@computer02 htmd]$ git status
# On branch newhtmddata
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#   (commit or discard the untracked or modified content in submodules)
#
#	modified:   data (untracked content)
#
no changes added to commit (use "git add" and/or "git commit -a")
[joao@computer02 htmd]$ 
```

**Comment by j3mdamas** [comment]
When you do a PR in the future that requires a change in the data, that PR will include a change in the commit of the htmd-data repo.

Yes, it will require you to commit to a different repo (which can be done git submodule commands), but IMO it also makes PRs much more readable, because all the data "noise" will be out of the PR

**Comment by stefdoerr** [comment]
```
stefan@spectre:~/Work/htmd/htmd$ git status
On branch newhtmddata
Your branch is up-to-date with 'origin/newhtmddata'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../buildmemb/

nothing added to commit but untracked files present (use "git add" to track)
stefan@spectre:~/Work/htmd/htmd$ git remote -v
origin	https://github.com/Acellera/htmd.git (fetch)
origin	https://github.com/Acellera/htmd.git (push)
stefan@spectre:~/Work/htmd/htmd$ cd data
stefan@spectre:~/Work/htmd/htmd/data$ git status
On branch newhtmddata
Your branch is up-to-date with 'origin/newhtmddata'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../../buildmemb/

nothing added to commit but untracked files present (use "git add" to track)
stefan@spectre:~/Work/htmd/htmd/data$ git remote -v
origin	https://github.com/Acellera/htmd.git (fetch)
origin	https://github.com/Acellera/htmd.git (push)
stefan@spectre:~/Work/htmd/htmd/data$ ll
total 20
drwxr-xr-x  5 stefan stefan 4096 may 15 20:05 ./
drwxr-xr-x 20 stefan stefan 4096 may 15 20:05 ../
drwxr-xr-x  2 stefan stefan 4096 may 15 20:05 1kdx/
drwxr-xr-x  2 stefan stefan 4096 may 15 20:05 metricdistance/
drwxr-xr-x  4 stefan stefan 4096 may 15 20:05 molecule-readers/
```
Why does it not have the correct remote when I check out this branch?

**Comment by stefdoerr** [comment]
Cool I checked it and it works good with the separate repo. I'm convinced :)

**Comment by j3mdamas** [comment]
It will be a bit of a turmoil with existing branches, but we'll have to manage it. Cool, I'll merge and release.

**Pull request merged**
