### PR TITLE
Pull request #1 in the process of terminating multiscalelab htmd fork

### PR DESCRIPTION
**Pull request by j3mdamas**

### CODE REVIEW

**Comment by stefdoerr** [comment]
Hm this will fail all travis builds on acellera :P Because right now I am
on a commit that fails. I will try to resolve it tomorrow though. Should be
easy I think.

**Comment by j3mdamas** [comment]
Well, it's a pull request, so no biggie. Tomorrow we'll see.

On Tue, Jul 12, 2016 at 8:10 PM, Stefan <notifications@github.com> wrote:

> Hm this will fail all travis builds on acellera :P Because right now I am
> on a commit that fails. I will try to resolve it tomorrow though. Should be
> easy I think.
>
> On Tue, Jul 12, 2016 at 8:08 PM, João M. Damas <notifications@github.com>
> wrote:
>
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/Acellera/htmd/pull/84
> > Commit Summary
> >
> > - started writing a general topology consistency checker
> > - empty() now sets a null box. This also fixes view() on prepared
> > molecules
> > - fixed issues with charmm building applying double patches and
> > doubling parameters and topologies
> > - Merge branch 'master' of https://github.com/multiscalelab/htmd
> > - added crd reader. no more pdb writing/reading from tleap
> > - log protonations
> > - added 3PTB test for charmm build
> > - Merge branch 'master' of https://github.com/multiscalelab/htmd
> > - added amber build test for 3PTB
> > - forgot to add the data
> > - added ambermini to travis.yml so that we can test amber build
> > - disabled amber test because tleap is nondeterministic in the cap
> > positions and I can't fix it's RNG
> > - readded pdb writing to amber.build but through my own write method
> > - added a shallow test for amber just compring the main prmtop fields
> > - Merge branch 'master' into bettertoporeader
> > - removed xtc file and moved readers
> > - moved most readers. need some cleaning still
> > - moved all readers and writers except PDB
> > - added dtypes and dimensions for Molecule. fixed bugs
> > - made universal topology reader
> > - replaced prmtop and psf readers as well
> > - psf reader works
> > - prmtop and crd reading works
> > - fixed _pdb_fields to _dtypes in preparation
> > - fixed another dtype problem
> > - fixed numatoms issue
> > - fixed bond removing in amber
> > - fixed disulfide bridges in amber
> > - fixed amber test for bonds
> > - cleanup
> > - improved olecule empty method
> > - updated amber test files
> > - fixed order of topology/coords setting. mol2 works now
> > - added more tests for readers. updated ligand binding tutorial
> > - correctly scale esp
> > - Merge branch 'master' of github.com:multiscalelab/htmd
> > - get multipoles and mulliken charges
> > - autodetect # of cpus
> > - First commit of new parameterisation code
> > - copyright messages in param source
> > - newparam testset
> > - ad import os to cli.py
> > - run tests
> > - remove duff inline tests from newparam
> > - run.sh
> > - disabled Matts agg matplotlib because I could not see any plots
> > anymore
> > - Merge branch 'master' of https://github.com/multiscalelab/htmd
> > - reuse points esp grid if it already exists
> > - Merge branch 'master' of github.com:multiscalelab/htmd
> > - worked on mae reader a bit
> > - added gwpca, fixed docs in ktri and added error in tica at bad
> > lagtime
> > - redesigned metricdihedral to allow any kinds of dihedrals and help
> > in defining manually
> > - added mindistance calculation to MetricDistance
> > - made background of VMD black again. was too annoying white
> > - added mindist files
> > - fixed minor bug in metricdistance mindistance calc
> > - Merge branch 'master' of https://github.com/multiscalelab/htmd
> > - forgot the tracer
> > - extended the C code to support multiframe coordinates. now I can
> > loop the frames in C as well if need be
> > - fixed amber writing parameter files into the tleap file
> > - min distance done entirely in C. removed deprecated projections
> > - fixed building of mindistance for all platforms
> > - added C distance building to travis for all platforms. let's test
> > - trying again the conda build C
> > - trying again building the C code
> > - fix for building in travis
> > - fixed argument passing to build script
> > - trying to debug weird travis behaviour
> > - commit spam
> > - found out the issue with the C compilation in travis
> > - build.sh file needed to be removed. crossing fingers
> > - forgot dummy rule in makefile
> >
> > File Changes
> >
> > - *M* .travis.yml
> > <https://github.com/Acellera/htmd/pull/84/files#diff-0> (2)
> > - *A* C/distance/Makefile
> > <https://github.com/Acellera/htmd/pull/84/files#diff-1> (33)
> > - *A* C/distance/mindist_ext.c
> > <https://github.com/Acellera/htmd/pull/84/files#diff-2> (114)
> > - *M* htmd/builder/amber.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-3> (56)
> > - *M* htmd/builder/charmm.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-4> (62)
> > - *M* htmd/builder/preparation.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-5> (38)
> > - *M* htmd/builder/residuedata.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-6> (26)
> > - *A* htmd/data/molecule-readers/3AM6/structure.crd
> > <https://github.com/Acellera/htmd/pull/84/files#diff-7> (20296)
> > - *A* htmd/data/molecule-readers/3AM6/structure.pdb
> > <https://github.com/Acellera/htmd/pull/84/files#diff-8> (47394)
> > - *A* htmd/data/molecule-readers/3AM6/structure.prmtop
> > <https://github.com/Acellera/htmd/pull/84/files#diff-9> (140997)
> > - *A* htmd/data/molecule-readers/3L5E/ligand.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-10> (198)
> > - *A* htmd/data/molecule-readers/3L5E/protein.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-11> (12686)
> > - *A* htmd/data/molecule-readers/4RWS/structure.pdb
> > <https://github.com/Acellera/htmd/pull/84/files#diff-12> (75358)
> > - *A* htmd/data/molecule-readers/4RWS/structure.psf
> > <https://github.com/Acellera/htmd/pull/84/files#diff-13> (164232)
> > - *A* htmd/data/molecule-readers/4RWS/traj.xtc
> > <https://github.com/Acellera/htmd/pull/84/files#diff-14> (0)
> > - *A* htmd/data/test-amber-build/3PTB/input.pdb
> > <https://github.com/Acellera/htmd/pull/84/files#diff-15> (7190)
> > - *A* htmd/data/test-amber-build/3PTB/leap.log
> > <https://github.com/Acellera/htmd/pull/84/files#diff-16> (3764)
> > - *A* htmd/data/test-amber-build/3PTB/log.txt
> > <https://github.com/Acellera/htmd/pull/84/files#diff-17> (71)
> > - *A* htmd/data/test-amber-build/3PTB/structure.crd
> > <https://github.com/Acellera/htmd/pull/84/files#diff-18> (3600)
> > - *A* htmd/data/test-amber-build/3PTB/structure.pdb
> > <https://github.com/Acellera/htmd/pull/84/files#diff-19> (14387)
> > - *A* htmd/data/test-amber-build/3PTB/structure.prmtop
> > <https://github.com/Acellera/htmd/pull/84/files#diff-20> (25423)
> > - *A* htmd/data/test-amber-build/3PTB/tleap.in
> > <https://github.com/Acellera/htmd/pull/84/files#diff-21> (24)
> > - *A* htmd/data/test-charmm-build/3PTB/0.top_all36_prot.rtf
> > <https://github.com/Acellera/htmd/pull/84/files#diff-22> (1777)
> > - *A* htmd/data/test-charmm-build/3PTB/1.top_water_ions.rtf
> > <https://github.com/Acellera/htmd/pull/84/files#diff-23> (113)
> > - *A* htmd/data/test-charmm-build/3PTB/2.top_all36_prot_arg0.rtf
> > <https://github.com/Acellera/htmd/pull/84/files#diff-24> (296)
> > - *A* htmd/data/test-charmm-build/3PTB/build.vmd
> > <https://github.com/Acellera/htmd/pull/84/files#diff-25> (174)
> > - *A* htmd/data/test-charmm-build/3PTB/log.txt
> > <https://github.com/Acellera/htmd/pull/84/files#diff-26> (243)
> > - *A* htmd/data/test-charmm-build/3PTB/parameters
> > <https://github.com/Acellera/htmd/pull/84/files#diff-27> (3712)
> > - *A* htmd/data/test-charmm-build/3PTB/segment0.pdb
> > <https://github.com/Acellera/htmd/pull/84/files#diff-28> (1644)
> > - *A* htmd/data/test-charmm-build/3PTB/segmentI.pdb
> > <https://github.com/Acellera/htmd/pull/84/files#diff-29> (9)
> > - *A* htmd/data/test-charmm-build/3PTB/segmentWT0.pdb
> > <https://github.com/Acellera/htmd/pull/84/files#diff-30> (3672)
> > - *A* htmd/data/test-charmm-build/3PTB/structure.pdb
> > <https://github.com/Acellera/htmd/pull/84/files#diff-31> (6906)
> > - *A* htmd/data/test-charmm-build/3PTB/structure.psf
> > <https://github.com/Acellera/htmd/pull/84/files#diff-32> (16721)
> > - *D* htmd/molecule/bincoor.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-33> (60)
> > - *M* htmd/molecule/molecule.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-34> (457)
> > - *D* htmd/molecule/prmtop.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-35> (104)
> > - *D* htmd/molecule/psf.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-36> (247)
> > - *A* htmd/molecule/readers.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-37> (606)
> > - *M* htmd/molecule/support.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-38> (30)
> > - *M* htmd/molecule/vmdparser.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-39> (78)
> > - *A* htmd/molecule/writers.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-40> (122)
> > - *D* htmd/molecule/xtc.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-41> (191)
> > - *A* htmd/newparameterization/cli.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-42> (59)
> > - *A* htmd/newparameterization/detectequivalents.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-43> (108)
> > - *A* htmd/newparameterization/detectsoftdihedrals.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-44> (213)
> > - *A* htmd/newparameterization/ff.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-45> (383)
> > - *A* htmd/newparameterization/ffevaluate.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-46> (221)
> > - *A* htmd/newparameterization/ffmolecule.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-47> (711)
> > - *A* htmd/newparameterization/fftype.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-48> (69)
> > - *A* htmd/newparameterization/phi.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-49> (147)
> > - *M* htmd/parameterization/__init__.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-50> (4)
> > - *A* htmd/projections/gwpca.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-51> (80)
> > - *M* htmd/projections/kmeanstri.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-52> (3)
> > - *M* htmd/projections/metricdihedral.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-53> (455)
> > - *M* htmd/projections/metricdistance.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-54> (174)
> > - *M* htmd/projections/metricshell.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-55> (99)
> > - *A* htmd/projections/mindist/Makefile
> > <https://github.com/Acellera/htmd/pull/84/files#diff-56> (5)
> > - *A* htmd/projections/mindist/mindist_ext.so
> > <https://github.com/Acellera/htmd/pull/84/files#diff-57> (0)
> > - *M* htmd/projections/tica.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-58> (2)
> > - *M* htmd/projections/util.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-59> (122)
> > - *M* htmd/qm/qmcalculation.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-60> (81)
> > - *M* htmd/vmdviewer.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-61> (2)
> > - *M* package/htmd/build.sh
> > <https://github.com/Acellera/htmd/pull/84/files#diff-62> (2)
> > - *M* package/htmd/meta.yaml
> > <https://github.com/Acellera/htmd/pull/84/files#diff-63> (3)
> > - *M* tests/mjh/test_xtc.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-64> (68)
> > - *A* tests/parameterise/reference/list
> > <https://github.com/Acellera/htmd/pull/84/files#diff-65> (119)
> > - *A* tests/parameterise/reference/m001/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-66> (55)
> > - *A* tests/parameterise/reference/m002/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-67> (42)
> > - *A* tests/parameterise/reference/m003/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-68> (49)
> > - *A* tests/parameterise/reference/m004/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-69> (48)
> > - *A* tests/parameterise/reference/m005/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-70> (36)
> > - *A* tests/parameterise/reference/m006/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-71> (33)
> > - *A* tests/parameterise/reference/m007/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-72> (30)
> > - *A* tests/parameterise/reference/m008/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-73> (24)
> > - *A* tests/parameterise/reference/m009/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-74> (54)
> > - *A* tests/parameterise/reference/m010/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-75> (42)
> > - *A* tests/parameterise/reference/m011/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-76> (30)
> > - *A* tests/parameterise/reference/m012/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-77> (54)
> > - *A* tests/parameterise/reference/m013/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-78> (43)
> > - *A* tests/parameterise/reference/m014/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-79> (45)
> > - *A* tests/parameterise/reference/m015/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-80> (39)
> > - *A* tests/parameterise/reference/m016/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-81> (36)
> > - *A* tests/parameterise/reference/m017/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-82> (30)
> > - *A* tests/parameterise/reference/m018/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-83> (40)
> > - *A* tests/parameterise/reference/m019/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-84> (58)
> > - *A* tests/parameterise/reference/m020/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-85> (52)
> > - *A* tests/parameterise/reference/m021/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-86> (64)
> > - *A* tests/parameterise/reference/m022/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-87> (46)
> > - *A* tests/parameterise/reference/m023/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-88> (34)
> > - *A* tests/parameterise/reference/m024/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-89> (43)
> > - *A* tests/parameterise/reference/m025/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-90> (34)
> > - *A* tests/parameterise/reference/m026/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-91> (43)
> > - *A* tests/parameterise/reference/m027/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-92> (49)
> > - *A* tests/parameterise/reference/m028/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-93> (43)
> > - *A* tests/parameterise/reference/m029/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-94> (37)
> > - *A* tests/parameterise/reference/m030/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-95> (40)
> > - *A* tests/parameterise/reference/m031/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-96> (24)
> > - *A* tests/parameterise/reference/m032/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-97> (39)
> > - *A* tests/parameterise/reference/m033/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-98> (36)
> > - *A* tests/parameterise/reference/m034/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-99> (60)
> > - *A* tests/parameterise/reference/m035/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-100> (42)
> > - *A* tests/parameterise/reference/m036/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-101> (30)
> > - *A* tests/parameterise/reference/m037/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-102> (40)
> > - *A* tests/parameterise/reference/m038/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-103> (34)
> > - *A* tests/parameterise/reference/m039/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-104> (28)
> > - *A* tests/parameterise/reference/m040/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-105> (18)
> > - *A* tests/parameterise/reference/m041/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-106> (41)
> > - *A* tests/parameterise/reference/m042/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-107> (45)
> > - *A* tests/parameterise/reference/m043/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-108> (45)
> > - *A* tests/parameterise/reference/m044/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-109> (45)
> > - *A* tests/parameterise/reference/m045/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-110> (43)
> > - *A* tests/parameterise/reference/m046/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-111> (37)
> > - *A* tests/parameterise/reference/m047/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-112> (39)
> > - *A* tests/parameterise/reference/m048/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-113> (39)
> > - *A* tests/parameterise/reference/m049/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-114> (35)
> > - *A* tests/parameterise/reference/m050/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-115> (39)
> > - *A* tests/parameterise/reference/m051/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-116> (39)
> > - *A* tests/parameterise/reference/m052/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-117> (33)
> > - *A* tests/parameterise/reference/m053/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-118> (38)
> > - *A* tests/parameterise/reference/m054/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-119> (47)
> > - *A* tests/parameterise/reference/m055/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-120> (41)
> > - *A* tests/parameterise/reference/m056/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-121> (36)
> > - *A* tests/parameterise/reference/m057/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-122> (30)
> > - *A* tests/parameterise/reference/m058/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-123> (41)
> > - *A* tests/parameterise/reference/m059/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-124> (41)
> > - *A* tests/parameterise/reference/m060/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-125> (26)
> > - *A* tests/parameterise/reference/m061/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-126> (38)
> > - *A* tests/parameterise/reference/m062/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-127> (50)
> > - *A* tests/parameterise/reference/m063/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-128> (44)
> > - *A* tests/parameterise/reference/m064/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-129> (32)
> > - *A* tests/parameterise/reference/m065/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-130> (50)
> > - *A* tests/parameterise/reference/m066/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-131> (38)
> > - *A* tests/parameterise/reference/m067/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-132> (44)
> > - *A* tests/parameterise/reference/m068/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-133> (32)
> > - *A* tests/parameterise/reference/m069/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-134> (56)
> > - *A* tests/parameterise/reference/m070/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-135> (47)
> > - *A* tests/parameterise/reference/m071/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-136> (44)
> > - *A* tests/parameterise/reference/m072/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-137> (32)
> > - *A* tests/parameterise/reference/m073/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-138> (26)
> > - *A* tests/parameterise/reference/m074/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-139> (56)
> > - *A* tests/parameterise/reference/m075/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-140> (68)
> > - *A* tests/parameterise/reference/m076/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-141> (50)
> > - *A* tests/parameterise/reference/m077/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-142> (44)
> > - *A* tests/parameterise/reference/m078/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-143> (38)
> > - *A* tests/parameterise/reference/m079/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-144> (42)
> > - *A* tests/parameterise/reference/m080/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-145> (33)
> > - *A* tests/parameterise/reference/m081/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-146> (39)
> > - *A* tests/parameterise/reference/m082/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-147> (40)
> > - *A* tests/parameterise/reference/m083/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-148> (46)
> > - *A* tests/parameterise/reference/m084/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-149> (40)
> > - *A* tests/parameterise/reference/m085/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-150> (49)
> > - *A* tests/parameterise/reference/m086/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-151> (40)
> > - *A* tests/parameterise/reference/m087/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-152> (43)
> > - *A* tests/parameterise/reference/m088/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-153> (28)
> > - *A* tests/parameterise/reference/m089/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-154> (37)
> > - *A* tests/parameterise/reference/m090/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-155> (26)
> > - *A* tests/parameterise/reference/m091/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-156> (28)
> > - *A* tests/parameterise/reference/m092/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-157> (45)
> > - *A* tests/parameterise/reference/m093/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-158> (54)
> > - *A* tests/parameterise/reference/m094/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-159> (48)
> > - *A* tests/parameterise/reference/m095/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-160> (60)
> > - *A* tests/parameterise/reference/m096/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-161> (42)
> > - *A* tests/parameterise/reference/m097/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-162> (48)
> > - *A* tests/parameterise/reference/m098/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-163> (42)
> > - *A* tests/parameterise/reference/m099/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-164> (66)
> > - *A* tests/parameterise/reference/m100/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-165> (30)
> > - *A* tests/parameterise/reference/m101/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-166> (36)
> > - *A* tests/parameterise/reference/m102/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-167> (39)
> > - *A* tests/parameterise/reference/m103/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-168> (39)
> > - *A* tests/parameterise/reference/m104/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-169> (22)
> > - *A* tests/parameterise/reference/m105/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-170> (37)
> > - *A* tests/parameterise/reference/m106/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-171> (34)
> > - *A* tests/parameterise/reference/m107/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-172> (28)
> > - *A* tests/parameterise/reference/m108/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-173> (45)
> > - *A* tests/parameterise/reference/m109/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-174> (42)
> > - *A* tests/parameterise/reference/m110/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-175> (36)
> > - *A* tests/parameterise/reference/m111/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-176> (36)
> > - *A* tests/parameterise/reference/m112/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-177> (41)
> > - *A* tests/parameterise/reference/m113/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-178> (39)
> > - *A* tests/parameterise/reference/m114/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-179> (30)
> > - *A* tests/parameterise/reference/m115/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-180> (34)
> > - *A* tests/parameterise/reference/m116/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-181> (36)
> > - *A* tests/parameterise/reference/m117/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-182> (34)
> > - *A* tests/parameterise/reference/m118/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-183> (37)
> > - *A* tests/parameterise/reference/m119/input.mol2
> > <https://github.com/Acellera/htmd/pull/84/files#diff-184> (20)
> > - *A* tests/parameterise/reference/run.sh
> > <https://github.com/Acellera/htmd/pull/84/files#diff-185> (16)
> > - *M* tests/run_inline_file_tests.py
> > <https://github.com/Acellera/htmd/pull/84/files#diff-186> (2)
> > - *M* tutorials/ligand-binding-analysis.ipynb
> > <https://github.com/Acellera/htmd/pull/84/files#diff-187> (1123)
> >
> > Patch Links:
> >
> > - https://github.com/Acellera/htmd/pull/84.patch
> > - https://github.com/Acellera/htmd/pull/84.diff
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Acellera/htmd/pull/84>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AHkVgqSbJ9phG1-g7IVotYn-7oEKJ1EDks5qU9gcgaJpZM4JKqh2
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/pull/84#issuecomment-232131021>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AKTzQi0DCqtlJA4I0b_l0f5XmprL8qV2ks5qU9h_gaJpZM4JKqh2>
> .
>



--

**Comment by j3mdamas** [comment]
do you need help?

**Comment by stefdoerr** [comment]
Are you worried about my last commit message? :D

**Comment by j3mdamas** [comment]
yes! :X

**Comment by stefdoerr** [comment]
If the last change doesn't work I am out of ideas. Will tell you.

**Pull request closed without merging**
