### PR TITLE
Replace old ffevaluate with numba

### PR DESCRIPTION
**Pull request by stefdoerr**

### CODE REVIEW

**Comment by stefdoerr** [comment]
@raimis I opened the PR. If you want check out the PR and run the tests and see if you like the fits. I looked at them and they were perfect. There is only that one case where the final energy dropped from 9 to 7 for dihedral despite the perfect fit.

**Comment by stefdoerr** [comment]
Actually I'll try to find out what's up with that change in dihedral energy. Bothers me too much

On February 13, 2018 4:44:02 PM GMT+01:00, Raimondas Galvelis <notifications@github.com> wrote:
>Assigned #564 to @stefdoerr.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/pull/564#event-1471908647

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by j3mdamas** [comment]
@stefdoerr I just changed the assignment to match the reviewer, as that's what makes sense to me

**Comment by stefdoerr** [comment]
I think assigning is for theone responsible for fixing it. The reviewer is the reviewer

**Comment by j3mdamas** [comment]
I see. So, assignee == original poster (in general). OK.

**Comment by j3mdamas** [comment]
Should we merge this for 1.12 (which I'm probably going to create soon) or maybe only later?

**Comment by stefdoerr** [comment]
later. I think it might become obsolete. I'm about to refactor parameterize

**Comment by j3mdamas** [comment]
OK; marked it to 1.14.x

**Pull request closed without merging**
