### PR TITLE
added reporting to the wait method of queues to show progress of calc…

### PR DESCRIPTION
**Pull request by stefdoerr**
…ulations

### CODE REVIEW

**Comment by stefdoerr** [comment]
No wait I am rethinking it a bit

**Comment by stefdoerr** [comment]
Okay I think now the logic makes more sense. If the reporting time is shorter than the sleeping time then the sleeping time should be equal to the reporting time. If the reporting time is longer than the sleeping time it should report every round(reporttime/sleeptime) iterations.

**Comment by stefdoerr** [comment]
Thought I might as well add a callback argument for playmolecule in case Gerard wants to make it look nice

**Comment by j3mdamas** [comment]
all of these new need the preparation fix which is not merged into master yet

**Comment by stefdoerr** [comment]
I know

**Comment by stefdoerr** [comment]
@j3mdamas can ye review pliz?

**Comment by stefdoerr** [comment]
Although this one actually would have needed some testing :P

**Comment by j3mdamas** [comment]
do you want me to test it?

**Comment by stefdoerr** [comment]
If you feel like it :P You would need some fake sleep-WU to test it

**Pull request merged**
